---
title: "SDS410: Capstone in SDS"
---

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQXbu3ro3ZPOf6oDatGpGSRTKPeopwoQcXUR0V_VmJEFrtnZ_Y0JpOP11R0bAqPp-P2qzupMNXT-oNd/pubhtml?gid=2049438587&amp;single=true&amp;widget=true&amp;headers=false" width="100%" height="810">

</iframe>

------------------------------------------------------------------------


<!--

1. Due before Thursday: Write down your notes/reflections for Retrospective 2 in your [Group Norms Google Doc](https://docs.google.com/spreadsheets/d/1eTXqqSXiLjZozH0XwhP5eCIwhPKaiwxIf3VvgyN-Sbw/edit#gid=1908015001)

-->


# Lec 11.2: Thu 11/16

## Announcements

1. In [Roster](https://docs.google.com/spreadsheets/d/1eTXqqSXiLjZozH0XwhP5eCIwhPKaiwxIf3VvgyN-Sbw/edit#gid=50606575) Google Sheet, please fill in your attendance for Tuesday's Sprint 2 demo and retrospective.
1. 



## Today

1. Discuss term paper (click "Term Paper" tab on top left of webpage) 
1. Ethics discussions   
    1.  Part III - Group XXX: [Discussion topic](https://www.dropbox.com/s/p4x4bzn4fl8126s/RAT%20Discussion%20Guide.pdf?dl=0) 21
    1.  Part III - Group XX: [Discussion topic](https://www.dropbox.com/s/p4x4bzn4fl8126s/RAT%20Discussion%20Guide.pdf?dl=0) 22
    1. Complete Ethics Reflections by next lecture Tue 11/21




------------------------------------------------------------------------




# Lec 11.1: Tue 11/14

## Announcements

- Sprint 2 demos and retrospective [agenda](https://docs.google.com/document/d/1gSzAzhvCA0ShQIjy0GWsBMOUwqkHANp2w2q9Xe8uXdo/edit) are moved to Tue 11/21 because Megan is sick today. Given tight schedule and importance of topics, on-time attendance is required.
- Put on your radars:
    - All groups need to schedule an end of project presentation to all sponsor stakeholders and myself between Mon 12/18 and Wed 12/20. Schedule this by emailing everyone as soon as exam schedule is released
    - Term paper due Thu 12/21 3pm: Structure to be discussed this Thursday.
- Ethics discussion this Thursday on Race After Technology Part IV. Groups 2-5 are up since Group 1 Delfina has gone twice so far. 

## Today

1. 




------------------------------------------------------------------------



# Lec 10.2: Thu 11/9

## Announcements

- Prof Shiya Cao & Prof. Scott LaCombe substituting today
- Sprint 2 demo and retrospective next lecture

## Today

- Work on Sprint II



------------------------------------------------------------------------



# Lec 10.1: Tue 11/7

## Announcements

- Prof Shiya Cao substituting today

## Today

- Work on Sprint II



------------------------------------------------------------------------



# Lec 9.1: Tue 10/31

## Today

- Work on Sprint II



------------------------------------------------------------------------



# Lec 8.2: Thu 10/26

## Announcements

Ethics discussions

1.  Part III - Group 4 IBM: [Discussion topic](https://www.dropbox.com/s/p4x4bzn4fl8126s/RAT%20Discussion%20Guide.pdf?dl=0) 21
1.  Part III - Group 1 Delfina: [Discussion topic](https://www.dropbox.com/s/p4x4bzn4fl8126s/RAT%20Discussion%20Guide.pdf?dl=0) 22


## Today



------------------------------------------------------------------------



# Lec 8.1: Tue 10/24

## Announcements



## Today

- Test editing and `term_paper.Rmd` committing changes to GitHub. 


------------------------------------------------------------------------



# Lec 7.2: Thu 10/19

## Today

Ethics discussions

1.  Part II - Group 3 Honda: [Discussion topic](https://www.dropbox.com/s/p4x4bzn4fl8126s/RAT%20Discussion%20Guide.pdf?dl=0) 15
1.  Part II - Group 2 Federal Reserve : [Discussion topic](https://www.dropbox.com/s/p4x4bzn4fl8126s/RAT%20Discussion%20Guide.pdf?dl=0) 16


## Ethics reflection

1.  Go to Roster Google Sheet, Individuals tab
2.  In Google Doc: Part II, write your takeaways from the class discussion on discussion topic. Photos of the whiteboard with the in-class discussion notes are on Slack in `#general`
3.  Max of two paragraphs for each reflection
4.  Due by Tue 10/24 before class.




------------------------------------------------------------------------



# Lec 7.1: Tue 10/17

## Announcements

1. Thursday: Ethics [discussion](https://www.dropbox.com/s/p4x4bzn4fl8126s/RAT%20Discussion%20Guide.pdf?dl=0) Race After Technology - Part II. Two groups chosen at random from: Group 2 Federal Reserve, Group 3 Honda, Group 4 IBM. Reflection will be due Tue after 10/24.


## Today

1. Sprint 1 demos and retrospective [agenda](https://docs.google.com/document/d/1YRYBDR2P1Sorwhzg7C1eMFIQ8VnITBOcAKvHwaUYPTA/edit) for today
1. Due before Thursday: Write down your notes/reflections for Retrospective 1 in your [Group Norms Google Doc](https://docs.google.com/spreadsheets/d/1eTXqqSXiLjZozH0XwhP5eCIwhPKaiwxIf3VvgyN-Sbw/edit#gid=1908015001)



------------------------------------------------------------------------


# Lec 6.2: Thu 10/12

## Today

1. Attempt 2: Knit term paper document. If you were **NOT** able to knit `term_paper.Rmd` last lecture: 
    1. Install the `tinytex` package
    1. Run `tinytex::install_tinytex()`. If you get a warning that "a LaTeX distribution may have existed in the system." say yes anyways.
    1. Open and close RStudio
    1. Try knitting `term_paper/term_paper.Rmd` again. If you get a warning that you need to run `tinytex::reinstall_tinytex()`, do so.
    1. If are now able to knit, update your answer in the Roster Google Sheet -> Individuals tab
    1. **If you were NOT able** to knit the document, take a screenshot of your error message, go to Slack `#general` and reply to the thread with it. 
1.  New tab on top-left of webpage [Sprints](sprints.html)

------------------------------------------------------------------------

# Lec 5.2: Thu 10/5

## Today

1.  Try knitting in your group's repos: `term_paper/term_paper.Rmd`
2.  Answer poll question in Roster Google Sheet, Individuals tab
3.  Work on Sprint 1

------------------------------------------------------------------------

# Lec 5.1: Tue 10/3

## Today

1.  Roster Google Sheet: Can you all clone your project repo?
2.  Code review exercies
    1.  Product owner/manager for Sprint 1 will upload the file I sent on Slack earlier to your repo
    2.  Each of you: Create a new branch
    3.  Each of you: Edit the file I sent. You can do this directly on GitHub.com
    4.  Each of you: Create pull request
    5.  Code review:
3.  See screencast if you forget any of these steps
4.  Work on Sprint 1

------------------------------------------------------------------------

# Lec 4.2: Thu 9/28

## Today

Ethics discussions

1.  Intro - Group 5 Sittercity: [Discussion topic](https://www.dropbox.com/s/p4x4bzn4fl8126s/RAT%20Discussion%20Guide.pdf?dl=0) 8
2.  Part I - Group 1 Delfina: [Discussion topic](https://www.dropbox.com/s/p4x4bzn4fl8126s/RAT%20Discussion%20Guide.pdf?dl=0) 13

## Ethics reflection

1.  Go to Roster Google Sheet, Individuals tab
2.  In Google Doc: for both Intro and Part I, write your takeaways from the class discussion on the chosen topic number
3.  Max of two paragraphs for each reflection
4.  Due by Tue 10/3 before class.

------------------------------------------------------------------------

# Lec 4.1: Tue 9/26

## Announcements

1.  Go to Roster Google Sheet and indicate whether you were able to clone your group's GitHub repo
2.  Ethics discussion on Thursday

## Today

Intermediate GitHub: Advanced collaboration (beyond just pushes, pulls, and commits).

1.  GitHub repo branches: `master` (default) and new branches
2.  When to commit/push changes directly to `master` versus creating a branch
3.  What's the difference between creating a branch versus a fork?
4.  Pull requests: merge changes into other branches

See screencasts tab on top-right of this page for demos on how to do this.

------------------------------------------------------------------------

# Lec 3.2: Thu 9/21

## Announcements

1.  Mountain Day thoughts?
2.  Resources to learn new tech:
    1.  Full access to all [DataCamp courses](https://app.datacamp.com/) for duration of semester; check your smith.edu email for invitation. Note: DataCamp is not without [controversy](https://www.buzzfeednews.com/article/daveyalba/datacamp-sexual-harassment-metoo-tech-startup), but with an educational license no money is exchanged.
    2.  Full access to all [LinkedIn Learning](https://www.linkedin.com/learning/) curriculum.
3.  Questions about ethics readings

## Today

1.  Look at Roster Google Sheet, Groups tab, "Project GitHub Folder" column
    1.  Make sure you can see repo. If not, check email for GitHub.com invitation
2.  Terminology:
    1.  *Agile project management* is an iterative approach to delivering a project throughout its life cycle.
    2.  *Scrum* is an agile project management framework that helps teams structure and manage their work through a set of values, principles, and practices. [Video](https://www.atlassian.com/agile/scrum)
    3.  *Kanban boards*: [Video](https://www.atlassian.com/agile/kanban)
3.  GitHub Projects Kanban board
4.  GitHub issues

## For next class

Make sure you can clone, i.e. make a local copy, of your project repo. If you need a refresher, go to "Screencast" tab on top right and watch "2022-09-08 Cloning a GitHub repo"

------------------------------------------------------------------------

# Lec 2.2: Thu 9/14

1.  Reading for the semester:
    1.  [Race After Technology](https://www.ruhabenjamin.com/)
    2.  Access eBook by clicking on link on top left
    3.  See schedule for readings
    4.  Look Roster Google Sheet, individuals tab
2.  Write down your [group norms](https://drive.google.com/drive/u/1/folders/1GKbMG3SfTthIhdxStvz_8cC7DMQNjBWE) from Lec 2.1
3.  Group norming exercise:
    1.  Go over and sign our new [capstone pponsor Agreement](https://drive.google.com/file/d/1fHtlKT0l9WHOJ1AHRDLk_MeD5ljOS6CC/view?usp=drive_link)
    2.  We will re-visit this during our blameless postmortem of semester during final lecture 15.2 on Thu 12/14
4.  Admin
    1.  Join [GitHub organization](https://github.com/orgs/sds-capstone/teams/2023-09-fall) for this course
    2.  Slack norms
    3.  [Playlist](https://open.spotify.com/playlist/7DotIpDU7lgiABDtGx2Sx6?si=81657e78591e4a0f)

------------------------------------------------------------------------

# Lec 2.1: Tue 9/12

1.  Move the desks and sit with your groups
2.  Go over webpage, in particular "Roster" Google Sheet
3.  In Slack `#general`, answer two polls on proposed readings for the semester.
4.  Documents for today
    1.  [Introduction to Teamwork](https://docs.google.com/document/u/1/d/1uqFmcTM7lKNowxxB0EV1LdimRctvC500BNAHf8ACD9Q/edit)
    2.  [Themes from Advice for Spring 23 Capstone from Fall 22 Capstone](https://docs.google.com/document/d/1dD-pfpLPEhuGSVi1JZhnEDoqGpPuZ0VaE3oB_KtN-ug/edit)
    3.  [SDS Capstone Sponsor Agreement](https://drive.google.com/file/d/1fHtlKT0l9WHOJ1AHRDLk_MeD5ljOS6CC/view?usp=drive_link)

------------------------------------------------------------------------

# Lec 1.2: Thu 9/7

## 1. Announcements

1.  Introductions
2.  Go over [webpage](https://rudeboybert.github.io/SDS410/) and syllabus (click website tab)
3.  Mantra board
4.  Go over TODO's
5.  Meet our [project sponsors](https://drive.google.com/drive/u/1/folders/1TrLOulA4ux3liGciRnmtvy8VvDa1jdBa)

## 2. Immediate TODOs

1.  By **tomorrow Friday 9am** I need your info:
    1.  Complete [project selection form](https://www.google.com/url?q=https://docs.google.com/forms/d/e/1FAIpQLSdkp5SoRzi4yWLc-prmAw6GFUT53O2Qwtk_a_x_xVnIz6LZcQ/viewform&sa=D&source=docs&ust=1694434817684137&usg=AOvVaw28QZ6kLyU_N_uPGOYQ1iOv)
    2.  Complete [intro survey](https://docs.google.com/forms/d/e/1FAIpQLSf_6W6yCNin1_SbwZMogj0lBbW5UjREcu8E1GRfABOZm2F0_g/viewforms)
2.  By **tomorrow noon** I will create groups:
    1.  I will create 5 groups and match groups to sponsors
    2.  I will create channels in Slack for each group and add all members
    3.  I will designate an interim group leader to ensure Sunday TODOs are done
3.  By **Sunday 5pm** contact sponsor by email to set weekly meeting time:
    1.  Interim group leader will take charge just for this weekend and schedule group zoom meeting
    2.  As a group, come up with 3-4 hour long time slots you can all meet for your weekly meeting with your sponsor
    3.  Designate someone to send email to sponsor (emails here: 410 Groups, Group Members), cc'ing all group members and me and Prof. Shiya Cao (who will be teaching capstone in the spring): akim04\@smith.edu scao53\@smith.edu
        1.  Introduce yourselves as students in Smith College SDS' capstone course
        2.  Include all proposed hour long time slots, ask if they work. I've communicated with the sponsors that this meeting should be an hour long and at a consistent time. 1.State your appreciation for sponsors agreeing to give their time

## 3. TODOs for before Tuesday's lecture

[Megan Lyster](https://www.google.com/url?q=https://www.smith.edu/academics/faculty/megan-lyster&sa=D&source=docs&ust=1694434775921986&usg=AOvVaw0cGjsP-inVcpQk5FLrNa-p) from Wurtele Center for first of four sessions on managing group dynamics:

1.  Read [Themes from Advice for Spring 23 Capstone from Fall 22 Capstone](https://docs.google.com/document/d/1dD-pfpLPEhuGSVi1JZhnEDoqGpPuZ0VaE3oB_KtN-ug/edit)
2.  Read [SDS Capstone Sponsor Agreement](https://drive.google.com/file/d/1fHtlKT0l9WHOJ1AHRDLk_MeD5ljOS6CC/view?usp=drive_link)
